title = "CanaryEngine"
gitRepoUrl = "https://github.com/canary-development/CanaryEngine"
gitSourceBranch = "main"

changelog = true

apiCategories = [
    "Event"
]

[navbar.logo]
alt = "CanaryEngine"
src = "navbar.png"

[[navbar.items]]
href = "https://discord.gg/cwwcZtqJAt"
label = "Discord"
position = "right"

[[navbar.items]]
href = "https://trello.com/b/fTJOmMua/canaryengine"
label = "Trello"
position = "right"

[[classOrder]]
section = "Framework APIs"
collapsed = true
classes = ["CanaryEngine", "CanaryEngineServer", "CanaryEngineClient", "CanaryEngineReplicated"]

[[classOrder]]
section = "Networking"
collapsed = true
classes = ["NetworkControllerServer", "NetworkControllerClient"]

[[classOrder]]
section = "Signals"
collapsed = true
classes = ["SignalControllerObject"]

[[classOrder]]
section = "Data APIs"
collapsed = true
classes = ["EasyProfile", "ProfileStoreObject", "ProfileObject"]

[[classOrder]]
section = "Engine APIs"
collapsed = true
classes = ["EngineLoader", "EngineDebugger", "EngineTypes"]

[[classOrder]]
section = "Runtime"
collapsed = true
classes = ["EngineRuntime", "EngineRuntimeContext", "EngineRuntimeSettings"]

[[classOrder]]
section = "Benchmarking"
collapsed = true
classes = ["Benchmark", "BenchmarkObject"]

[[classOrder]]
section = "Libraries"
collapsed = true
classes = ["Sprite", "Base64", "Statistics", "Utility", "Fetch", "UIShelf", "MDify"]

[[classOrder]]
section = "Library Objects"
collapsed = true
classes = ["TopBarIconObject", "TopBarSpacerObject"]

[docusaurus]
projectName = "CanaryEngine"
tagline = "The lightweight and optimized framework"
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"
favicon = "favicon.png"

[footer]
style = "dark"
copyright = "Copyright © 2023 Canary. Built with Moonwave"

[home]
enabled = true
includeReadme = false

[[home.features]]
title = "Type Safe 🦺"
description = "Strictly typed, along with native support for roblox-ts that can be found on the NPM marketplace."

[[home.features]]
title = "Secure 🔐"
description = "The networking system that CanaryEngine uses can actually partially prevent exploits like RemoteSpy from being easily useable."

[[home.features]]
title = "Optimized 🏃‍♀️"
description = "Extremely optimized, with most internal functions running fast along with custom signal and network implementations."