title = "CanaryEngine"
gitRepoUrl = "https://github.com/canary-development/CanaryEngine"
gitSourceBranch = "main"

changelog = true

[docusaurus]
projectName = "CanaryEngine"
tagline = "The lightweight and optimized framework"
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"
favicon = "favicon.png"

[footer]
style = "dark"
copyright = "Copyright © 2023 lolmansReturn. Built with Moonwave and Docusaurus"

[home]
enabled = true
includeReadme = false