title = "CanaryEngine"
gitRepoUrl = "https://github.com/canary-development/CanaryEngine"
gitSourceBranch = "main"

changelog = true

apiCategories = [
    "Event",
    "Enum"
]

[navbar.logo]
alt = "CanaryEngine"
src = "navbar.png"

[[navbar.items]]
href = "https://discord.gg/cwwcZtqJAt"
label = "Discord"
position = "right"

[[navbar.items]]
href = "https://trello.com/b/fTJOmMua/canaryengine"
label = "Trello"
position = "right"

[[classOrder]]
section = "Framework"
collapsed = true
classes = ["CanaryEngine", "CanaryEngineServer", "CanaryEngineClient", "CanaryEngineReplicated"]

[[classOrder]]
section = "Engine"
collapsed = true
classes = ["EngineLoader", "EngineDebugger", "EngineTypes"]

[[classOrder]]
section = "Runtime"
collapsed = true
classes = ["EngineRuntime", "EngineRuntimeContext", "EngineRuntimeSettings"]

[[classOrder]]
section = "Networking"
collapsed = true
classes = ["NetworkControllerServer", "NetworkControllerClient"]

[[classOrder]]
section = "Signals"
collapsed = true
classes = ["SignalControllerObject"]

[[classOrder]]
section = "Data Management"
collapsed = true
classes = ["EasyProfile", "ProfileStoreObject", "ProfileObject"]

[[classOrder]]
section = "Libraries"
collapsed = true
classes = ["Sprite", "Base64", "Statistics", "Fetch", "UIShelf", "TopBarIconObject", "TopBarSpacerObject", "MDify", "Benchmark", "BenchmarkObject"]

[docusaurus]
projectName = "CanaryEngine"
tagline = "A lightweight framework with both performance & usability in mind"
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"
favicon = "favicon.png"

[footer]
style = "dark"
copyright = "Copyright © 2023 Canary. Built with Moonwave"

[home]
enabled = true
includeReadme = false

[[home.features]]
title = "Type Safe 🦺"
description = "Strictly typed, with multiple interfaces available for each included library. A roblox-ts file is also included to use."

[[home.features]]
title = "Secure 🔐"
description = "The networking system that CanaryEngine uses can actually partially prevent exploits like RemoteSpy from being easily useable."

[[home.features]]
title = "Optimized 🏃‍♀️"
description = "Extremely optimized, with most internal functions running fast along with custom signal and network implementations."