title = "CanaryEngine"
gitRepoUrl = "https://github.com/canary-development/CanaryEngine"

changelog = true

[docusaurus]
projectName = "CanaryEngine"
tagline = "The lightweight and optimized framework"
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"
favicon = "favicon.png"
url = "https://canary-development.github.io"
baseUrl = "/docs/CanaryEngine"

[footer]
style = "dark"
copyright = "Copyright © 2023 lolmansReturn. Built with Moonwave and Docusaurus"

[home]
enabled = true
includeReadme = false