title = "CanaryEngine"
gitRepoUrl = "https://github.com/canary-development/CanaryEngine"

changelog = true

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"
favicon = ""

[navbar]
hideableSidebar = true

[footer]
style = "dark"
copyright = "Copyright © 2023 lolmansReturn. Built with Moonwave and Docusaurus"
