name = "daemon/framework"
version = "11.0.0"
description = "A featherlight framework for Luau games"
authors = ["Daemon6109"]
repository = "https://github.com/Daemon6109/framework"
license = "MIT"
includes = [
    "dist/src",
    "pesde.toml",
    "README.md",
    "LICENSE"
]

[target]
environment = "roblox"
lib = "dist/init.luau"
build_files = ["dist"]

[indices]
default = "https://github.com/daimond113/pesde-index"
[wally_indices]
default = "https://github.com/UpliftGames/wally-index"
[scripts]

roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"

[dev_dependencies]
scripts = { name = "pesde/scripts_rojo", version = "^0.1.0", target = "lune" }
rojo = { name = "pesde/rojo", version = "^7.4.4", target = "lune" }
stylua = { name = "pesde/stylua", version = "^2.0.1", target = "lune" }
Jest = { wally = "jsdotlua/jest", version = "^3.10.0" }
JestGlobals = { wally = "jsdotlua/jest-globals", version = "^3.10.0" }

[dependencies]
Debugger = { name = "lumin/debugger", version = "^1.0.3" }