name = "daemon/framework"
version = "10.0.1"
description = "A featherlight framework for Luau games"
authors = ["Daemon6109"]
repository = "https://github.com/Daemon6109/framework"
license = "MIT"
includes = [
  "pesde.toml",
  "src",
]

[target]
environment = "roblox"
lib = "src/init.luau"
build_files = ["src"]

[indices]
default = "https://github.com/daimond113/pesde-index"

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"

[dev_dependencies]
scripts = { name = "pesde/scripts_rojo", version = "^0.1.0", target = "lune" }
rojo = { name = "pesde/rojo", version = "^7.4.4", target = "lune" }
stylua = { name = "pesde/stylua", version = "^2.0.1", target = "lune" }

[dependencies]
debugger = { name = "lumin/debugger", version = "^1.0.0" }

