# This file lists tools managed by Rokit, a toolchain manager for Roblox projects.
# For more information, see https://github.com/rojo-rbx/rokit

# New tools can be added by running `rokit add <tool>` in a terminal.

[tools]
darklua = "seaofvoices/darklua@0.16.0"
lune = "lune-org/lune@0.8.9"
rojo = "UpliftGames/rojo@7.4.0-uplift.syncback.rc.20"
run-in-roblox = "rojo-rbx/run-in-roblox@0.3.0"
selene = "Kampfkarren/selene@0.28.0"
StyLua = "JohnnyMorganz/StyLua@2.0.2"