[package]
name = "canary-development/canaryengine"
version = "5.0.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
future = "red-blox/future@1.0.1"
signal = "red-blox/signal@2.0.1"
ratelimit = "red-blox/ratelimit@1.0.1"
red = "lolmansreturn/red-backend@1.1.2"