[package]
name = "lumin/framework"
description = "A lightning fast & amazing game framework for Roblox"
version = "9.0.0-rc4"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
promise = "lukadev-0/typed-promise@4.0.2"
signal = "sleitnick/signal@2.0.1"
spawn = "red-blox/spawn@^1.0.0"

[dev-dependencies]
net = "lumin/net@0.1.0"

[place]
shared-packages = "game.ReplicatedStorage.Packages"