name: Draft

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
    contents: write
    pages: write
    id-token: write

jobs:
    bump:
        name: Bump Versions
        runs-on: ubuntu-latest
        outputs:
          release-body: ${{ steps.update-changelog.outputs.release-notes }}
        steps:
          - name: Checkout repository
            uses: actions/checkout@v4
            with:
              ref: "main"

          - name: Update changelog
            id: update-changelog
            uses: thomaseizinger/keep-a-changelog-new-release@3.1.0
            with:
              tag: ${{ github.ref_name }}
              changelogPath: "docs/changelog.md"

          - name: Commit and push
            uses: EndBug/add-and-commit@v9
            with:
              message: Bump version to ${{ github.ref_name }}
              default_author: github_actions

    publish-build:
        name: Publish Assets
        runs-on: ubuntu-latest
        needs: bump
        steps:
          - name: Checkout Repository
            uses: actions/checkout@v4

          - name: Setup Rokit
            uses: CompeyDev/setup-rokit@v0.1.0

          - name: Install Wally dependencies
            run: wally install

          - name: Generate sourcemap
            run: rojo sourcemap standalone.project.json --output sourcemap.json

          - name: Generate package types
            run: wally-package-types --sourcemap sourcemap.json Packages

          - name: Format code
            run: stylua src/

          - name: Build standalone
            run: rojo build standalone.project.json --output ./Standalone.rbxm

          - name: Draft release
            uses: softprops/action-gh-release@v2.0.8
            with:
              tag_name: ${{ github.ref_name }}
              name: ${{ github.ref_name }}
              prerelease: ${{ contains(github.ref_name, 'rc') }}
              generate_release_notes: true
              body: |
                ## Changelog
                ${{ needs.bump.outputs.release-body }}
              files: |
                ./Standalone.rbxm

    publish-package:
        name: Publish Package
        runs-on: ubuntu-latest
        needs: bump
        steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Setup Rokit
          uses: CompeyDev/setup-rokit@v0.1.0

        - name: Log In
          run: |
            wally login --token "${{secrets.WALLY_AUTH_TOKEN}}"

        - name: Publish
          run: |
            wally publish
